version: '3.8'

services:
  backend:
    build:
      context: ./movie-sentiment-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./movie-sentiment-backend:/app
    command: python main.py
    networks:
      - sentiment-network

  frontend:
    build:
      context: ./movie-sentiment-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - sentiment-network
    environment:
      - REACT_APP_API_URL=http://backend:8000

networks:
  sentiment-network:
    driver: bridge
